version: '3.7'

services:

  react-frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/srv/app/nickylai-admin-client/'
      - '/srv/app/nickylai-admin-client/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development