version: '3'

services:

  server:
    container_name: finance_tracker_backend
    build: ./server
    image: nximage/finance_tracker_backend
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      API_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/src:/srv/app/fr-shohin-admin-server/src
    command: npm run dev
    networks:
      - finance_tracker_network

  client:
    container_name: finance_tracker_frontend
    build: ./client
    image: nximage/finance_tracker_frontend:${TAG}
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/srv/app/fr-shohin-admin-client/src
      - ./client/public:/srv/app/fr-shohin-admin-client/public
    command: npm run start
    depends_on: 
      - server
    networks:
      - finance_tracker_network

networks: 
  finance_tracker_network:
    driver: bridge
