export const ADD_RECORD_REQUEST = "ADD_RECORD_REQUEST";

export const ADD_RECORD_SUCCESS = "ADD_RECORD_SUCCESS";

export const ADD_RECORD_FAILURE = "ADD_RECORD_FAILURE";


export const LOAD_RECORDS_REQUEST = "LOAD_RECORDS_REQUEST";

export const LOAD_RECORDS_SUCCESS = "LOAD_RECORDS_SUCCESS";

export const LOAD_RECORDS_FAILURE = "LOAD_RECORDS_FAILURE";


export const UPDATE_RECORD_REQUEST = "UPDATE_RECORD_REQUEST";

export const UPDATE_RECORD_SUCCESS = "UPDATE_RECORD_SUCCESS";

export const UPDATE_RECORD_FAILURE = "UPDATE_RECORD_FAILURE";


export const DELETE_RECORD_REQUEST = "DELETE_RECORD_REQUEST";

export const DELETE_RECORD_SUCCESS = "DELETE_RECORD_SUCCESS";

export const DELETE_RECORD_FAILURE = "DELETE_RECORD_FAILURE";


export const OPEN_ADD_RECORD_MODAL = "OPEN_ADD_RECORD_MODAL";

export const CLOSE_ADD_RECORD_MODAL = "CLOSE_ADD_RECORD_MODAL";

export const OPEN_EDIT_RECORD_MODAL = "OPEN_EDIT_RECORD_MODAL";

export const CLOSE_EDIT_RECORD_MODAL = "CLOSE_EDIT_RECORD_MODAL";

export const OPEN_DELETE_RECORD_MODAL = "OPEN_DELETE_RECORD_MODAL";

export const CLOSE_DELETE_RECORD_MODAL = "CLOSE_DELETE_RECORD_MODAL";

