export const ADD_RECORD = "ADD_RECORD";

export const RECORDS_DATA_LOADED = "RECORDS_DATA_LOADED";

export const LOAD_RECORDS_REQUEST = "LOAD_RECORDS_REQUEST";

export const LOAD_RECORDS_SUCCESS = "LOAD_RECORDS_SUCCESS";

export const LOAD_RECORDS_FAILURE = "LOAD_RECORDS_FAILURE";

export const CHANGE_PAYER = "CHANGE_PAYER";